import javax.swing.*;
import java.awt.*;
import java.io.File;

public class AddDelLab extends javax.swing.JFrame {

    /**
     * Creates new form Password
     */

    private javax.swing.JButton ConfirmButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField Lab_tf;
    private javax.swing.JLabel txt_Lab;
    private javax.swing.JPanel Color_BG;
    private javax.swing.JPanel detail;

    public AddDelLab() {
        initComponents();

        try {
            // Load and register the font
            Font appleFont = Font.createFont(Font.TRUETYPE_FONT, new File("OOP/src/Font/Big Apple 3PM.ttf"));
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(appleFont);


            // Set the font for components
            setCustomFont(appleFont);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setCustomFont(Font font){
        txt_Lab.setFont(font.deriveFont(Font.PLAIN, 16));
        Lab_tf.setFont(font.deriveFont(Font.PLAIN, 16));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        txt_Lab = new javax.swing.JLabel();
        Lab_tf = new javax.swing.JTextField();
        ConfirmButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        Color_BG = new javax.swing.JPanel();
        detail = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(275, 150));
        setResizable(false);
        setBackground(new java.awt.Color(84, 59, 45));
        setTitle("Add&Delete Lab");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Lab.setForeground(new java.awt.Color(255, 255, 255));
        txt_Lab.setText("Lab");

        Lab_tf.setBackground(new java.awt.Color(175, 130, 104));
        Lab_tf.setForeground(new java.awt.Color(255, 255, 255));
        Lab_tf.setForeground(new java.awt.Color(204, 204, 204));
        Lab_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lab_tfActionPerformed(evt);
            }
        });

        ConfirmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button/confirmButtonSmallv2.png"))); // NOI18N
        ConfirmButton.setBorderPainted(false);
        ConfirmButton.setContentAreaFilled(false);
        ConfirmButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button/deleteButtonSmallv2.png"))); // NOI18N
        DeleteButton.setBorderPainted(false);
        DeleteButton.setContentAreaFilled(false);
        DeleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 59, 104, -1));

        detail.setOpaque(false);

        javax.swing.GroupLayout detailLayout = new javax.swing.GroupLayout(detail);
        detail.setLayout(detailLayout);
        detailLayout.setHorizontalGroup(
                detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(detailLayout.createSequentialGroup()
                                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(detailLayout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(txt_Lab)
                                                .addGap(15, 15, 15)
                                                .addComponent(Lab_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30))
                                        .addGroup(detailLayout.createSequentialGroup()
                                                .addGap(0, 0, 0)
                                                .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        detailLayout.setVerticalGroup(
                detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(detailLayout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_Lab)
                                        .addComponent(Lab_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ConfirmButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(DeleteButton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        getContentPane().add(detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 80));

        Color_BG.setBackground(new java.awt.Color(132, 99, 82));

        javax.swing.GroupLayout Color_BGLayout = new javax.swing.GroupLayout(Color_BG);
        Color_BG.setLayout(Color_BGLayout);
        Color_BGLayout.setHorizontalGroup(
                Color_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 280, Short.MAX_VALUE)
        );
        Color_BGLayout.setVerticalGroup(
                Color_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 170, Short.MAX_VALUE)
        );

        getContentPane().add(Color_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 170));

        pack();
    }// </editor-fold>

    private void Lab_tfActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDelLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDelLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDelLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDelLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDelLab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify

}
