/**
 *
 * @author Newtellafolk
 */
import java.awt.Color;

public class DeleteSeatMDI extends javax.swing.JFrame {

    /**
     * Creates new form DeleteSeatMDI
     */
    public DeleteSeatMDI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        seatId_label = new javax.swing.JLabel();
        enterSeatId = new javax.swing.JTextField();
        delete_label = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seatId_label.setFont(new java.awt.Font("Big Apple 3PM", 1, 16)); // NOI18N
        seatId_label.setForeground(new java.awt.Color(255, 244, 204));
        seatId_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seatId_label.setText("Seat ID");
        getContentPane().add(seatId_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 166, 75, -1));

        enterSeatId.setBackground(new java.awt.Color(79, 47, 19));
        enterSeatId.setFont(new java.awt.Font("Big Apple 3PM", 1, 12)); // NOI18N
        enterSeatId.setForeground(new java.awt.Color(245, 243, 230));
        enterSeatId.setText("Enter Seat ID");
        enterSeatId.setBorder(null);
        enterSeatId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enterSeatIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enterSeatIdFocusLost(evt);
            }
        });
        enterSeatId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterSeatIdActionPerformed(evt);
            }
        });
        getContentPane().add(enterSeatId, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 167, 90, 15));

        delete_label.setFont(new java.awt.Font("Big Apple 3PM", 1, 24)); // NOI18N
        delete_label.setForeground(new java.awt.Color(255, 244, 204));
        delete_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete_label.setText("Delete Seat");
        getContentPane().add(delete_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 37, 330, 30));

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("Image/deleteButtonSmall.png"))); // NOI18N
        deleteButton.setBorder(null);
        deleteButton.setBorderPainted(false);
        deleteButton.setContentAreaFilled(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 205, 330, -1));

        bg.setBackground(new java.awt.Color(84, 59, 45));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("Image/NewSeat (1).png"))); // NOI18N
        bg.setText("jLabel1");
        bg.setOpaque(true);
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 335, -1));

        pack();
    }// </editor-fold>                        

    private void enterSeatIdActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void enterSeatIdFocusGained(java.awt.event.FocusEvent evt) {
        if (enterSeatId.getText().equals("Enter Seat ID")){
            enterSeatId.setText("");
        }
        enterSeatId.setForeground(Color.WHITE);
    }

    private void enterSeatIdFocusLost(java.awt.event.FocusEvent evt) {
        if (enterSeatId.getText().equals("")){
            enterSeatId.setText("Enter Seat ID");
        }
    }

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteSeatMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteSeatMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteSeatMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteSeatMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteSeatMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel bg;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel delete_label;
    private javax.swing.JTextField enterSeatId;
    private javax.swing.JLabel seatId_label;
    // End of variables declaration                   
}