
import javax.swing.*;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.awt.Dimension;
import java.awt.Toolkit;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author armmy
 */
public class Password extends javax.swing.JFrame implements RoleChecker{

    /**
     * Creates new form Password
     */
    public Password() {
        this(null);
    }
    public Password(User user) {
        this.user = user;
        role = userType();
        initComponents();
        password_pwf.setFocusable(true);

        try{
            File fontStyle_apple = new File("OOP/src/Font/Big Apple 3PM.ttf");
            File fontStyle_minecraft = new File("OOP/src/Font/minecraft_font.ttf");
            Font font_welcome = Font.createFont(Font.TRUETYPE_FONT,fontStyle_apple).deriveFont(35f);
            Font font_nqueue = Font.createFont(Font.TRUETYPE_FONT,fontStyle_apple).deriveFont(60f);
            Font font_password = Font.createFont(Font.TRUETYPE_FONT,fontStyle_apple).deriveFont(30f);
            Font font_enter = Font.createFont(Font.TRUETYPE_FONT,fontStyle_minecraft).deriveFont(22f);
            Font font_confirm = Font.createFont(Font.TRUETYPE_FONT,fontStyle_apple).deriveFont(18f);
            welcome_l.setFont(font_welcome);
            nqueue_l.setFont(font_nqueue);
            password_l.setFont(font_password);
            enter_l.setFont(font_enter);
        }catch(Exception e){
            e.printStackTrace();

        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        nqueue_l = new javax.swing.JLabel();
        welcome_l = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enter_l = new javax.swing.JLabel();
        password_p = new javax.swing.JPanel();
        password_l = new javax.swing.JLabel();
        password_pwf = new javax.swing.JPasswordField();
        confirm_bt = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nqueue_l.setFont(new java.awt.Font("Segoe UI", 3, 60)); // NOI18N
        nqueue_l.setForeground(new java.awt.Color(255, 255, 255));
        nqueue_l.setText("N - QUEUE ");
        nqueue_l.setToolTipText("");
        nqueue_l.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(nqueue_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 390, 70));

        welcome_l.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        welcome_l.setForeground(new java.awt.Color(255, 255, 255));
        welcome_l.setText("Welcome to");
        getContentPane().add(welcome_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 360, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 68, 37, -1));

        enter_l.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        enter_l.setForeground(new java.awt.Color(255, 255, 255));
        enter_l.setText("Enter the secret code !");
        getContentPane().add(enter_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        password_p.setBackground(new java.awt.Color(255, 255, 255));
        password_p.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password_p.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password_l.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        password_l.setText("Password");
        password_p.add(password_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 9, 190, 52));

        password_pwf.setBackground(new java.awt.Color(235, 235, 235));
        password_pwf.setForeground(new java.awt.Color(153, 153, 153));
        password_pwf.setText("Input Password");
        password_pwf.setToolTipText("");
        password_pwf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_pwfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_pwfFocusLost(evt);
            }
        });
        password_pwf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_pwfActionPerformed(evt);
            }
        });
        password_p.add(password_pwf, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 9, 620, 52));

        getContentPane().add(password_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 820, 70));

        confirm_bt.setIcon(new javax.swing.ImageIcon("OOP/src/Image/confirmButtonFont.png")); // NOI18N
        confirm_bt.setBorderPainted(false);
        confirm_bt.setContentAreaFilled(false);
        confirm_bt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirm_btMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirm_btMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirm_btMouseExited(evt);
            }
        });
        confirm_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_btActionPerformed(evt);
            }
        });
        getContentPane().add(confirm_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, -1, -1));

        bg.setBackground(new java.awt.Color(84, 59, 45));
        bg.setIcon(new javax.swing.ImageIcon("OOP/src/Image/bgArm.png")); // NOI18N
        bg.setOpaque(true);
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        pack();
    }// </editor-fold>

    private void confirm_btActionPerformed(java.awt.event.ActionEvent evt) {
        String temp_pass = String.valueOf(password_pwf.getPassword());
        if (this.role == 1) {
            TA t_a = (TA) user;
            if (t_a.getPassword().equals(temp_pass)) {
                JOptionPane.showMessageDialog(null, "Welcome to NQUEUE");
                this.dispose();
                MainPage mainpage = new MainPage(new TA());
                mainpage.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Invalid password", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else if (this.role == 2) {
            Professor pfs = (Professor) user;
            if (pfs.getPassword().equals(temp_pass)) {
                JOptionPane.showMessageDialog(null, "Welcome to NQUEUE");
                this.dispose();
                MainPage mainpage = new MainPage(new Professor());
                mainpage.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Invalid password", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void password_pwfActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void password_pwfFocusGained(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        if(password_pwf.getText().equals("Input Password")){
            password_pwf.setText("");
        }

        password_pwf.setForeground(Color.black);
    }

    private void password_pwfFocusLost(java.awt.event.FocusEvent evt) {

        if(password_pwf.getText().equals("")){
            password_pwf.setText("Input Password");
        }
        //[153,153,153]
        password_pwf.setForeground(new Color(153,153,153));
    }

    private void confirm_btMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void confirm_btMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void confirm_btMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel bg;
    private javax.swing.JButton confirm_bt;
    private javax.swing.JLabel enter_l;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nqueue_l;
    private javax.swing.JLabel password_l;
    private javax.swing.JPanel password_p;
    private javax.swing.JPasswordField password_pwf;
    private javax.swing.JLabel welcome_l;
    private User user;
    private int role;

    @Override
    public int userType() {
        int role = 0;
        if (user instanceof Professor) {
            Professor prof = (Professor) user;
            role = prof.getRole();
        }  else if (user instanceof TA) {
            TA t_a = (TA) user;
            role = t_a.getRole();
        }
        return role;
    }
    // End of variables declaration
}
