/**
 *
 * @author Newtellafolk
 */


public class Waiting extends javax.swing.JDialog {

    /**
     *
     */
    public Waiting(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        lb_wait = new javax.swing.JLabel();
        board = new javax.swing.JLabel();
        bg_color = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusCycleRoot(false);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_wait.setFont(new java.awt.Font("Big Apple 3PM", 1, 22)); // NOI18N
        lb_wait.setForeground(new java.awt.Color(87, 65, 43));
        lb_wait.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wait.setText("Please Wait A Moment...");
        getContentPane().add(lb_wait, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 75, 465, -1));

        board.setBackground(new java.awt.Color(84, 59, 45));
        board.setForeground(new java.awt.Color(84, 59, 45));
        board.setIcon(new javax.swing.ImageIcon(getClass().getResource("Image/Waitting&YourQ(470, 160).png"))); // NOI18N
        getContentPane().add(board, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bg_color.setBackground(new java.awt.Color(84, 59, 45));
        getContentPane().add(bg_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 160));

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Waiting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Waiting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Waiting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Waiting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Waiting dialog = new Waiting(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel bg_color;
    private javax.swing.JLabel board;
    private javax.swing.JLabel lb_wait;
    // End of variables declaration
}
