/**
 *
 * @author Newtellafolk
 */
public class YourQ extends javax.swing.JDialog {

    /**
     * Creates new form YourQ
     */
    public YourQ(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lb_yourQ = new javax.swing.JLabel();
        bg_color = new javax.swing.JPanel();
        board = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_yourQ.setFont(new java.awt.Font("Big Apple 3PM", 1, 22)); // NOI18N
        lb_yourQ.setForeground(new java.awt.Color(87, 65, 43));
        lb_yourQ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_yourQ.setText("Good Luck You're Next!");
        getContentPane().add(lb_yourQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 75, 465, -1));

        bg_color.setBackground(new java.awt.Color(84, 59, 45));

        board.setIcon(new javax.swing.ImageIcon(getClass().getResource("Image/Waitting&YourQ(470, 160).png"))); // NOI18N

        javax.swing.GroupLayout bg_colorLayout = new javax.swing.GroupLayout(bg_color);
        bg_color.setLayout(bg_colorLayout);
        bg_colorLayout.setHorizontalGroup(
                bg_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_colorLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(board))
        );
        bg_colorLayout.setVerticalGroup(
                bg_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_colorLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(board))
        );

        getContentPane().add(bg_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 160));

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YourQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YourQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YourQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YourQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                YourQ dialog = new YourQ(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel bg_color;
    private javax.swing.JLabel board;
    private javax.swing.JLabel lb_yourQ;
    // End of variables declaration                   
}